import Head from "next/head";

import { Inter } from "next/font/google";
import { Box } from "@chakra-ui/react";
import { Navbar } from "@/components/molecules";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>techShore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.jpg" />
      </Head>

      <Box>
        <Navbar></Navbar>
      </Box>
    </>
  );
}
